### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by Thubs** [EndeavourOS-Community-Editions/bspwm#12]
When I log in the background loads up but as soon as the taskbar loads it puts me back at the log in screen.

**Comment by flyingcakes85** [comment]
If you have another DE/WM installed on the machine where you can log in, then please do the following:

1. `sudo pacman -S xorg-server-xephyr`
2. `Xephyr -br -ac -noreset -screen 800x600 :1`
3. Open another terminal and run `DISPLAY=:1 bspwm`
4. Errors should be printed in terminal. See if there is something concerning in there, or paste the output here.


In case you don't have another DE/WM installed, then you could do the following

1. `Ctrl+Alt+F2` to land into a TTY
2. Enter your login details
3. `echo "exec bspwm" > .xinitrc`
4. `startx`

This should launch bspwm, and after the crash, it will land back in tty. See if there are any fatal errors printed there.

**Comment by Thubs** [comment]
What I was trying to say was I didn't have a chance to do anything to recover my system there was no chance to open a terminal even. This was after a clean install which I attempted on a VM and actual hardware.

**Comment by flyingcakes85** [comment]
> What I was trying to say was I didn't have a chance to do anything to recover my system there was no chance to open a terminal even. This was after a clean install which I attempted on a VM and actual hardware.

I suppose you are still able to access the login screen? From your first post:

> When I log in the background loads up but as soon as the taskbar loads it puts me back at the **log in screen**.

From the login screen you can switch to a TTY and follow this:
> In case you don't have another DE/WM installed, then you could do the following
>
>  1.  Ctrl+Alt+F2 to land into a TTY
>  2.  Enter your login details
>  3.  echo "exec bspwm" > .xinitrc
>  4.  startx
>
> This should launch bspwm, and after the crash, it will land back in tty. See if there are any fatal errors printed there.

<hr>

On a side note, I suspect the issue doesn't have anything to do with bspwm. Its probably the kernel. Install the LTS kernel and try logging in again. 

1. On login screen, press `Ctrl+Alt+F2` to enter TTY.
2. Enter your login details
3. Run `sudo pacman -S linux-lts linux-lts-headers`
4. Run `sudo grub-mkconfig -o /boot/grub/grub.cfg`
5. Reboot, and on grub screen, select Linux LTS kernel
