### ISSUE TITLE
Installation on Arch Linux

### ISSUE THREAD

**Issue by DvrDania** [EndeavourOS-Community-Editions/bspwm#13]
Do I get all the configs from endeavourOS bspwm if I just install this on my fresh arch install? sorry im a noob.

**Comment by flyingcakes85** [comment]
Yes, you can clone the repo and use the bundled script to set it up.
You will still need to set up a display manager yourself (or use startx)

**Comment by DvrDania** [comment]
Got it, Thanks!

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/bspwm/blob/622ba43ce518d54fb9e538f84c4ca1630ad76ce1/packages-repository.txt#L42
some packages are from EndeavourOS repo but you can install them from AUR too.
You will need to edit the packages list on pure arch.
