### ISSUE TITLE
some users unable to login

### ISSUE THREAD

**Issue by sirlucidae** [EndeavourOS-Community-Editions/bspwm#14]
https://forum.endeavouros.com/t/just-installed-the-community-edition-cant-start-bspwm-goes-back-to-lightdm/18641/1

This forum bug report matches the description of at least one other report from the Telegram channel, and possibly more. And it seems that picom is being executed at startup by default. It might be better to comment out picom and leave it up to users to enable themselves.

**/bspwm/.config/bspwm/bspwmrc**
```
# Picom
picom -CGb &
```

**Comment by flyingcakes85** [comment]
Sounds like a good idea. Will update soon.

**Comment by flyingcakes85** [comment]
https://github.com/endeavouros-team/PKGBUILDS/pull/163
