### ISSUE TITLE
No Audio on latest installed bspwm and youtube stuttering (laggy)

### ISSUE THREAD

**Issue by thefool76** [EndeavourOS-Community-Editions/bspwm#19]
hey there!
today i installed endeavour 0S bwpm on my vmware workstation after all the setup i tried to check the audio and opened youtube on firefox when i clicked the video the video was laggy and stuttering alot and no audio . i check the audio button it where working fine i thought there must be some issue with vmware but i checked other linux os on my vmware it doesn't have any issue .

**Comment by flyingcakes85** [comment]
Hi!

This seems like an issue with the particular set up, or different packages. Could you please report this on the forum at [https://forum.endeavouros.com/](https://forum.endeavouros.com/).

**Comment by thefool76** [comment]
ok
