### ISSUE TITLE
Error while installing packages

### ISSUE THREAD

**Issue by raatkirandi** [EndeavourOS-Community-Editions/bspwm#26]
Can't go through with the script bash-install.sh because of missing package ttf-nerd-fonts-symbols.

A quick search for the package reveals 4 packages:

**community/ttf-nerd-fonts-symbols-1000-em** _2.2.1-5_
    High number of extra glyphs from popular 'iconic fonts' (1000-em)
**community/ttf-nerd-fonts-symbols-1000-em-mono** _2.2.1-5_
    High number of extra glyphs from popular 'iconic fonts' (1000-em monospace)
**community/ttf-nerd-fonts-symbols-2048-em** _2.2.1-5_
    High number of extra glyphs from popular 'iconic fonts' (2048-em)
**community/ttf-nerd-fonts-symbols-2048-em-mono** _2.2.1-5_
    High number of extra glyphs from popular 'iconic fonts' (2048-em monospace)

Faced the same error while installing this edition through calamares from liveUSB.

**Comment by vereym** [comment]
can confirm, I faced the same issue

**Comment by killajoe** [comment]
exchange it with ttf-nerd-fonts-symbols-2048-em (and use latest ISO)

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/bspwm/commit/3cf2c421020eb876609cab00e7e5510d9ce48efe
