### ISSUE TITLE
replace termite with alacritty

### ISSUE THREAD

**Issue by hitchho** [EndeavourOS-Community-Editions/bspwm#27]
termite has been for a quite awhile recommended in termite repo to be replaced with alacritty

**Comment by flyingcakes85** [comment]
We're using xfce4-terminal 

https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/sxhkd/sxhkdrc#L7

Is there some place where I mistakenly forgot to remove termite?

**Comment by hitchho** [comment]
https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/termite/config
https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/.config/gtk-3.0/gtk.css
seems to be termite related

**Comment by killajoe** [comment]
```
VteTerminal, vte-terminal {
    padding: 13px;
    
 }
```

applies to xfce4-terminal also ;)
