### ISSUE TITLE
bspwm config line-44: Is the `&` symbol missing ？

### ISSUE THREAD

**Issue by jqtmviyu** [EndeavourOS-Community-Editions/bspwm#29]
https://github.com/EndeavourOS-Community-Editions/bspwm/blob/89e5995588120def06961ddbee087bbd57d52962/.config/bspwm/bspwmrc#L44

**Comment by killajoe** [comment]
where?
https://github.com/jceb/dex

**Comment by jqtmviyu** [comment]
picom.conf look like not work well in bspwm environment. `inactive-opacity = xxx` not work , should fix by other setting `mark-ovredir-focused = false`

https://github.com/yshui/picom/issues/887#issuecomment-1237485160

**Comment by jqtmviyu** [comment]
> where? https://github.com/jceb/dex

at the line end. And the next line look like to start other programs. 

should add `&` between `dex -a -s /etc/xdg/autostart/:~/.config/autostart/` and `nm-applet --indicator &` ?  Maybe I wrong.

**Comment by killajoe** [comment]
ah yes i see.. i am not using bspwm and maintainer is [flyingcakes85](https://github.com/EndeavourOS-Community-Editions/bspwm/commits?author=flyingcakes85) mainly.. 
Looks legit to me as all others have the splitting & question is if it does cause any issue?

**Comment by flyingcakes85** [comment]
#30 meaning to fix it
