### ISSUE TITLE
feh --auto-zoom --scale-down inconsistent behavior for same command on bspwm

### ISSUE THREAD

**Issue by jqtmviyu** [EndeavourOS-Community-Editions/bspwm#31]
https://github.com/derf/feh/issues/494

It might be a better idea to replace it with other software, like `gpicview` or other little software. 
I spent quite a bit of time looking at it's help doc and finally found out that it has a problem with its zoom mode on bspwm/i3, unless I refresh it with the key `r` every time

**Comment by killajoe** [comment]
not really clear where the issue is with the BSPWM setup?

**Comment by flyingcakes85** [comment]
@jqtmviyu I understand the issue you linked to, but where does feh show up in bspwm configs?

**Comment by jqtmviyu** [comment]
> @jqtmviyu I understand the issue you linked to, but where does feh show up in bspwm configs?

https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/packages-repository.txt#L12

**Comment by jqtmviyu** [comment]
> @jqtmviyu I understand the issue you linked to, but where does feh show up in bspwm configs?

https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/packages-repository.txt#L12

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/blob/7f3edea9f663249fa306d8a5e5c77e2973446361/data/eos/modules/packagechooser_ce.conf#L72

the installer has it also, so if it is not used in any way could be removed?
