### ISSUE TITLE
there is no setup script used for iso installs currently on BSPWM?

### ISSUE THREAD

**Issue by killajoe** [EndeavourOS-Community-Editions/bspwm#32]
https://github.com/EndeavourOS-Community-Editions/bspwm/blob/main/xed.dconf
is not used but it is shipped with the skel package.
should we remove it or add a setup script to use it?

**Comment by flyingcakes85** [comment]
That can be removed from the repository. It was initially shipped, but I don't see a reason to have text editor configs in our packages.

**Comment by killajoe** [comment]
removed it.,.
