### ISSUE TITLE
Want to maintain this

### ISSUE THREAD

**Issue by kurayami07734** [EndeavourOS-Community-Editions/bspwm#42]
I had a lot of trouble while trying to install endeavour os bspwm edition

I've finally got it working

I don't want anyone to face similar hassle in setting this up

**Comment by marsjane** [comment]
Why no one respond? I think I need your experience.. I installed endeavour os i3wm version and install this repo script, but I cannot find the bspwm option in the login page, only old i3 and i3-debug. Do you have any ideas on this? Or is there any way I can install a clean endeavourOS with bspwm?

**Comment by killajoe** [comment]
to went into this you should first do a Pull Request.

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/bspwm?tab=readme-ov-file#unmaintained-needs-contributors-or-maintainer
