### ISSUE TITLE
Checkupdates script

### ISSUE THREAD

**Issue by Qpernicus** [EndeavourOS-Community-Editions/bspwm#8]
It seems the polybar checkupdates-script in this CE always shows 1 regardless if there are any updates. It also shows how many updates there are if they are more then 1. I used both sudo pacman as well as yay to update. Makes no difference. There always seems to be 1 update, never 0.

**Comment by flyingcakes85** [comment]
The script should now work as expected. 

Thanks for reporting :+1:
