### ISSUE TITLE
Forum link needs to be fixed

### ISSUE THREAD

**Issue by Scotty-Trees** [EndeavourOS-Community-Editions/bspwm#9]
On the main github page: https://github.com/EndeavourOS-Community-Editions/bspwm

Under the title: Get involved at our forum: https://forum.endeavouros.com/t/bspwm-edition

That link no longer works and should be updated and pointing towards: https://forum.endeavouros.com/c/desktop-environments/bspwm/75

Hope this helps :)

**Comment by flyingcakes85** [comment]
Thanks for the notice! 
I've edited the link on sidebar and the Readme.
